# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Clean CI DB 
      run: mvn flyway:clean
      env:
          FLYWAY_PASSWORD: ${{ secrets.DB2_PASSWD }}
          FLYWAY_USER: ${{ secrets.DB2_USERNAME }}
          FLYWAY_URL: ${{ secrets.DB2_JDBC_URL }}
    - name: Test DB Migration
      run: mvn flyway:migrate
      env: 
          FLYWAY_PASSWORD: ${{ secrets.DB2_PASSWD }}
          FLYWAY_USER: ${{ secrets.DB2_USERNAME }}
          FLYWAY_URL: ${{ secrets.DB2_JDBC_URL }}
  deploy:  
    name: Deploy
    runs-on: ubuntu-latest
    
    
    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: lateral-linker-276514
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
        with:
          args: app deploy app.yaml  
